version: '3'
services:
  jenkins:
    image: gcr.io/instruqt/jenkins:latest
    ports:
    - "8080:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - gitea
  gitea:
    image: gcr.io/instruqt/gitea:latest
    environment:
      - SSH_DOMAIN=gitea
      - ROOT_URL=http://gitea:3000/
      - ENABLE_ACCESS_LOG=true
    ports:
    - "3000:3000"